name: CMake on Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Debug to enable coverage)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Install dependencies on Ubuntu
      run: sudo apt-get update && sudo apt-get install -y libcmocka-dev gcovr gcc

    # Delete the CMake build directory to avoid cache issues
    - name: Clean the build directory
      run: rm -rf ${{github.workspace}}/build

    # Configure CMake in a 'build' subdirectory
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    # Build the project
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # Run the tests
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure -C ${{env.BUILD_TYPE}}

    # Generate code coverage report
    - name: Code coverage report
      working-directory: ${{github.workspace}}/build
      run: gcovr --root ${{github.workspace}} --exclude-directories "tests/" --branches --verbose --txt --output coverage.txt

    # Upload the coverage report as an artifact
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: ${{github.workspace}}/build/coverage.txt
